management/urls.py
from django.urls import path
from management import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'management'

urlpatterns = [
    path('', views.home, name='home'),
    path('signupuser/', views.signupuser, name='signupuser'),
    path('loginuser/', views.loginuser, name='loginuser'),
    path('logoutuser/', views.logoutuser, name='logoutuser'),
    
    path('myprofile/', views.myprofile, name='myprofile'),
    path('myprofile/updateprofile/', views.updateprofile, name='updateprofile'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

memory_album/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import (
    MemoryGalleryListView,
    MemoryGalleryDetailView,
    MemoryGalleryCreateView, 
    MemoryGalleryUpdateView, 
    MemoryGalleryDeleteView,
    MemoryGalleryFilterListView,
    MemoryGalleryFilterOtherListView,
)

app_name = 'memory_album'

urlpatterns = [
    path('', MemoryGalleryListView.as_view(), name='memory_album'),
    path('my_gallery/', MemoryGalleryFilterListView.as_view(), name='my_gallery'),
    path('photographer/', MemoryGalleryFilterOtherListView.as_view(), name='photographer'),
    path('create/', MemoryGalleryCreateView.as_view(), name='create'),
    path('<int:pk>/', MemoryGalleryDetailView.as_view(), name='detail'),
    path('<int:pk>/delete', MemoryGalleryDeleteView.as_view(), name='delete'),
    path('<int:pk>/update', MemoryGalleryUpdateView.as_view(), name='update'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

photographer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('management.urls')),
    path('memory_album/', include('memory_album.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

management/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from django.urls import reverse

def get_upload_path(instance, filename):
    return 'profile_photo/{0}/{1}'.format(instance.user.username, filename)
class Profile(models.Model):
    user = models.OneToOneField(User, 
                                on_delete=models.CASCADE
                                )
    introduction = models.TextField(blank=True, null=True)
    phone_number = models.IntegerField(blank=True, null=True)
    mobile_number = models.IntegerField(blank=True, null=True)
    work = models.CharField(max_length=500, blank=True, null=True)
    address = models.CharField(max_length=500, blank=True, null=True)
    website = models.CharField(max_length=500, blank=True, null=True)
    linked_in = models.CharField(max_length=500, blank=True, null=True)
    instagram = models.CharField(max_length=500, blank=True, null=True)
    twitter = models.CharField(max_length=500, blank=True, null=True)
    profile_photo = models.ImageField(upload_to=get_upload_path, default="default.jpg")
    
    
    def __str__(self):
        return str(self.user.first_name)
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.profile_photo.path)

        if img.height > 300 or img.width > 600:
            output_size = (300, 600)
            img.thumbnail(output_size)
            img.save(self.profile_photo.path)
    


    

management/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from management.models import Profile


class UserCreateForm(UserCreationForm):
    email = forms.EmailField(max_length=255, required=True)
    first_name = forms.CharField(max_length=255, required=True)
    last_name = forms.CharField(max_length=255, required=True)
    
    class Meta:
        model = User
        fields = ['username',
                  'first_name',
                  'last_name',
                  'email',
                  'password1',
                  'password2',
                  ]
        help_texts = {
            'username': None,
            'password1': None,
            'password2': None,
            'email': None,
        }
        
  
class UserEditForm(forms.ModelForm):
    email = forms.EmailField()
    
    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
        ]
        
class ProfileEditForm(forms.ModelForm):
    
    class Meta:
        model = Profile
        fields = [
            'introduction',
            'phone_number',
            'profile_photo',
            'work',
            'address',
            'website',
            'linked_in',
            'instagram',
            'twitter',
        ]
        

management/views.py
from django.shortcuts import render, redirect
from management.forms import UserCreateForm, ProfileEditForm, UserEditForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib import messages


def signupuser(request):
    """Create User"""
    if request.method == "POST":
        form = UserCreateForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            email = form.cleaned_data.get('email')
            first_name = form.cleaned_data.get('first_name')
            last_name = form.cleaned_data.get('last_name')
            password = form.cleaned_data.get('password')
            address = form.cleaned_data.get('address')
            website = form.cleaned_data.get('website')
            linked_in = form.cleaned_data.get('linked_in')
            instagram = form.cleaned_data.get('instagram')
            twitter = form.cleaned_data.get('twitter')
            message = messages.success(request, 
                                       f'User has been created')
            return redirect('management:signupuser')
    else:
        form = UserCreateForm()
    return render(request, 'management/signupuser.html', {'form':form})

def loginuser(request):
    """Login functionallity of the page"""
    if request.method == 'GET':
        return render(request, 
                      'management/loginuser.html',
                      {'form':AuthenticationForm()}
                      )
    else:
        user = authenticate(request,
                            username=request.POST['username'],
                            password=request.POST['password']
                            )
        if user is None:
            return render(request,
                          'management/loginuser.html',
                          {'form':AuthenticationForm(),
                           'error':'Username or Password is incorrect'}
                          )
        else:
            login(request, user)
            return redirect('management:home')
        
@login_required    
def logoutuser(request):
    """Logout functionallity of the page"""
    if request.method == "GET":
        logout(request)
        message = messages.success(request, 
                                   f'You are successfully logout!'
                                   )
        return render(request,
                      'management/logoutuser.html'
                      )
        
        
def home(request):
    """Show the Home page"""
    return render(request, 'management/home.html')


@login_required
def myprofile(request):
    return render(request, 'management/myprofile.html')
    

@login_required
def updateprofile(request):
    if request.method == "POST":
        u_form = UserEditForm(request.POST, instance=request.user)
        p_form = ProfileEditForm(request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            message = messages.success(request, f'Succesfully updated your profile')
            return redirect('management:myprofile')
    else:
        u_form = UserEditForm(instance=request.user)
        p_form = ProfileEditForm(instance=request.user.profile)
        context = {'u_form': u_form, 'p_form': p_form}
        
    return render(request, 'management/updateprofile.html', context)

management/templates/management/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

      <!-- Google Font -->
      <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,900" rel="stylesheet">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

    <!-- Bootstrap CDN and external CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'management/base.css' %}">
  </head>
  <body>
    <section id="main">

      <div class="container">

        <nav class="navbar navbar-expand-lg navbar-light bg-transparent">
          <a class="navbar-brand logo" href="{% url 'management:home' %}">Photo Booth</a>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'management:home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'memory_album:memory_album' %}">Gallery</a>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'management:myprofile' %}">My Profile</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'memory_album:my_gallery' %}">My Gallery</a>
              </li>
              {% endif %}
            </ul>
              <ul class="navbar-nav ml-auto">
              {% if user.is_authenticated %}
              <li class="nav-item ">
                <a class="nav-link" href="{% url 'management:logoutuser' %}">Logout</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'management:loginuser' %}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'management:signupuser' %}">Sign up</a>
              </li>
              {% endif %}
            </ul>
            
          </div>
        </nav>
      </div>
  </div>
    </section id="body">

      <section class="body-info">
        {% block content%}
        {% endblock%}
      </div>

    </section>

    <section id="footer">

    </section>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  </body>
</html>

management/templates/management/home.html
{% extends 'management/base.html' %}
{% load static %}
{% block content %}

{% endblock %}

management/templates/management/loginuser.html
{% extends 'management/base.html' %}
{% load bootstrap %}

{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{%static 'css/base.css'%}">
    <title>Document</title>
</head>
<body>
    {% block content %}
    <div class="container pt-2 pb-5 w-25 mt-5 border shadow">
        <form method="POST">
            <h1 class="text-center info-login mt-3 pt-1 header-info">Photo Booth</h1>
            <h2>Login</h2>
            {% csrf_token %}
            <p>{{ form|bootstrap }}</p>
            <div class="col text-center">
                <div class="row">
                    <div class="col text-center">
                    <button type="submit" class="btn btn-success">Login</button> 
                </div>  
                </div>
            </div>
        </form>
    </div>
</div>
    {% endblock %}

</body>
</html>

management/templates/management/logoutuser.html
{% extends 'management/base.html' %}
{% load static %}

management/templates/management/myprofile.html
{% extends 'management/base.html' %}
{% load bootstrap %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <title>Document</title>
</head>
<body>
    {% block content %}
    <section class="container" id="profile">
    {%if messages%}
        {%for message in messages%}
            <div class="container alert alert-{{ message.tags }} mt-2">
            <h6>{{ message }}</h6>
            </div>
        {% endfor %}
    {% endif %}
    <div class="container pt-3 ">
      
        <div class="main-body">
        
              <div class="row gutters-sm">
                <div class="col-md-4 mb-3">
                  <div class="card">
                    <div class="card-body">
                      <div class="d-flex flex-column align-items-center text-center">
                        <img src="{{ user.profile.profile_photo.url }}" alt="Admin" class="rounded-circle border shadow" width="250">
                        <div class="mt-3">
                          <h4>{{user.first_name}} {{user.last_name}}</h4>
                          <p class="text-secondary mb-1">{{user.profile.work}}</p>
                          <p class="text-muted font-size-sm">{{user.profile.address}}</p>
                          <form enctype="multipart/form-data" method="POST">
                            {% csrf_token %}
                            <a href="{% url 'management:updateprofile' %}" class="btn btn-primary" role="button" aria-pressed="true">Update</a>
                            </form>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="card mt-3 ">
                    <ul class="list-group list-group-flush">
                      <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap text-wrap">
                        <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-globe mr-2 icon-inline"><circle cx="12" cy="12" r="10"></circle><line x1="2" y1="12" x2="22" y2="12"></line><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"></path></svg>Website</h6>
                        <a class="text-secondary d-block w-100" href="{{user.profile.website}}">{{user.profile.website}}</a>
                        
                      </li>
                      <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                        <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-github mr-2 icon-inline"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>Linked in</h6>
                        <a class="text-secondary d-block w-100" href="{{user.profile.linked_in}}">{{user.profile.linked_in}}</a>
                      </li>
                      <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                        <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-twitter mr-2 icon-inline text-info"><path d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z"></path></svg>Twitter</h6>
                        <a class="text-secondary d-block w-100" href="{{user.profile.instagram}}">{{user.profile.instagram}}</a>
                      </li>
                      <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                        <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-instagram mr-2 icon-inline text-danger"><rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect><path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path><line x1="17.5" y1="6.5" x2="17.51" y2="6.5"></line></svg>Instagram</h6>
                        <a class="text-secondary d-block w-100" href="{{user.profile.twitter}}">{{user.profile.twitter}}</a>
                      </li>
                    </ul>
                  </div>
                </div>
                <div class="col-md-8">
                  <div class="card mb-3">
                    <div class="card-body">
                      <div class="row">
                        <div class="col-sm-3">
                          <h6 class="mb-0">Full Name</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            {{user.first_name}} {{user.last_name}}
                        </div>
                      </div>
                      <hr>
                      <div class="row">
                        <div class="col-sm-3">
                          <h6 class="mb-0">Email</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            {{user.email}}
                        </div>
                      </div>
                      <hr>
                      <div class="row">
                        <div class="col-sm-3">
                          <h6 class="mb-0">Mobile</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            {{user.profile.phone_number}}
                        </div>
                      </div>
                      <hr>
                      <div class="row">
                        <div class="col-sm-3">
                          <h6 class="mb-0">Address</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            {{user.profile.address}}
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="row gutters-sm" style="width: 103%; height: 66%;">
                    <div class="col-sm-6 mb-3 h-100 w-100">
                      <div class="card"  style="width: 212%; height: 66%;">
                        <div class="card-body" style='width: 102%; height: 66%;'>
                          <h6 class="d-flex align-items-center mb-5"><i class="material-icons text-info mr-2">Intro!</i></h6>
                          <p class="ml-3 mr-3 w-auto ">{{user.profile.introduction}}</p>
                        
                        </div>
                      </div>
                    </div>
                
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
        </div>
      </section>
        {% endblock %}
        
</body>
</html>

management/templates/management/signupuser.html
{% extends 'management/base.html' %}
{% load bootstrap %}

{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{%static 'css/base.css'%}">
    <title>Document</title>
</head>
<body>
    
    {% block content %}
    <div class="container pt-5 pb-3 mt-5 w-25 border shadow ">
        <form method="POST">
            <h2 class="text-center info-login pb-2 header-info">Photo Booth</h2>
            <h2>Join our Group!</h2>
            {% csrf_token %}
            <p>{{ form|bootstrap }}</p>
            <div class="col text-center p-0">
                    <button type="submit" class="btn btn-success">Sign up</button>
            </div>
        </form>
        {%if messages%}
        {%for message in messages%}
            <div class="alert alert-{{ message.tags }} mt-2">
            <h6>{{ message }}</h6>
        {% endfor %}
    {% endif %}
    </div>
    {% endblock %}

</body>
</html>

management/templates/management/updateprofile.html
{% extends 'management/base.html' %}
{% load bootstrap %}

{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{%static 'css/base.css'%}">
    <title>Document</title>
</head>
<body>
    
    {% block content %}
    <div class="container pt-5 pb-3 mt-5 border">
        <form enctype="multipart/form-data" method="POST">
            
            {% csrf_token %}
            <p>{{ u_form|bootstrap }}</p>
            <p>{{ p_form|bootstrap }}</p>
            <div class="col text-center p-0">
                    <button type="submit" class="btn btn-success">Update</button>
                    <button type="submit" class="btn btn-danger">Cancel</button>  
            </div>
        </form>
        {%if messages%}
        {%for message in messages%}
            <div class="alert alert-{{ message.tags }} mt-2">
            <h6>{{ message }}</h6>
        {% endfor %}
    {% endif %}
    </div>
    {% endblock %}

</body>
</html>